Repository scikit-learn-contrib/qolmat, pull requests merged in 2023-10, with the labels that each got.

#56 Feat: Diffusion models
  HISTORY.rst
  qolmat/benchmark/missing_patterns.py
  qolmat/imputations/diffusions/__init__py
  qolmat/imputations/diffusions/base.py
  qolmat/imputations/diffusions/ddpms.py
  qolmat/imputations/diffusions/utils.py
  qolmat/imputations/imputers.py
  qolmat/imputations/imputers_pytorch.py
  tests/imputations/test_imputers_diffusions.py
Labels: enhancement

#80 Gsa bench
  AUTHORS.rst
  HISTORY.rst
  README.rst
  examples/benchmark.md
  qolmat/benchmark/metrics.py
  qolmat/imputations/imputers.py
  qolmat/imputations/imputers_pytorch.py
  setup.py
  tests/imputations/test_imputers_pytorch.py
Labels: documentation

#110 Fix: the problem of a column including nans in test but training set
  qolmat/imputations/imputers.py
Labels: bug

#77 Docs: tutorial for diffusion models
  docs/api.rst
  docs/imputers.rst
  docs/index.rst
  examples/tutorials/plot_tuto_diffusion_models.py
Labels: documentation
